### PR TITLE
Fixes upgraded systems

### LINKED ISSUE #646: Upgrade to 0.9.3.1387 : not working
I had installed a former release candidate 0.9.3 and have just decided to install the stable version.

I copy the file to my server and have done the installation as required. All the lights were green.

I can have an access to Kimai, but nothing happens when I click on the Admin Panel button.

According to the debug, i have the following lines:
_[29.03.2016 13:35:46] E_WARNING in_array() expects parameter 2 to be array, null given @/home/monordi/kimai/extensions/ki_adminpanel/templates/scripts/activities.php line 52 
[29.03.2016 13:35:46] E_NOTICE Undefined index: projects @/home/monordi/kimai/extensions/ki_adminpanel/templates/scripts/activities.php line 52 
_

These lines are repeated at least 20 times.

The line 52 is the following:
	if (in_array($project['projectID'], $activity['projects'])) {

What should I do ? I am a little be lost.

Thank you very much for any help and I apologize for my poor English.

Jo Bart

### PR DESCRIPTION
**Pull request by kevinpapst**
FIXES #646

Changes proposed in this pull request:
- see discussion in #646 

Reason for this pull request:
- fixing upgraded systems, that stopped working

### CODE REVIEW

File: extensions/ki_adminpanel/templates/scripts/activities.php [hunk 1]
```diff
@@ -49,7 +49,7 @@
 					<?php
 					$activityProjects = array();
 					foreach($this->projects as $project) {
-						if (in_array($project['projectID'], $activity['projects'])) {
+						if (isset($activity['projects']) && in_array($project['projectID'], $activity['projects'])) {
```
Comment (simonschaufi) [inline extensions/ki_adminpanel/templates/scripts/activities.php:52]: how can i test this bug?

Comment (kevinpapst) [inline extensions/ki_adminpanel/templates/scripts/activities.php:52]: I guess I downloaded and installed https://github.com/kimai/kimai/releases/tag/v0.9.3-rc.1
and then did an upgrade with the current master.
After that just open the administration (and check your server logs)
