### PR TITLE
Fix: Show projects assigned to activity

### LINKED ISSUE #461: Show Project in the admin task list
When adding a task with the same name to several projects, you can not see the specific project of the task in the administration list. you have to open every single task to see the specific project. 
By adding the project to the admin task list, you can see the specific project for every task.

### PR DESCRIPTION
**Pull request by simonschaufi**
Fixes #461

### CODE REVIEW

File: extensions/ki_adminpanel/templates/scripts/activities.php [hunk 1]
```diff
@@ -48,14 +44,12 @@
...
-						if (isset($activity['projects']) && in_array($project['projectID'], $activity['projects'])) {
-							$name = $this->escape($project['name']) . ' (' . $this->escape($this->ellipsis($project['customerName'], 30)) . ')';
-							if ($project['visible'] != 1 || $project['customerVisible'] != 1) {
-								$name = '<span class="hidden">'.$name.'</span>';
-							}
-							$activityProjects[] = $name;
+					foreach($activity['projects'] as $project) {
+						$name = $this->escape($project['name']) . ' (' . $this->escape($this->ellipsis($project['customer_name'], 30)) . ')';
+						if (!$project['visible']) {
+							$name = '<span class="hidden">' . $name . '</span>';
```
Comment (kevinpapst) [inline extensions/ki_adminpanel/templates/scripts/activities.php:50]: The $project['customerVisible'] != 1 check is gone now, why?

Comment (simonschaufi) [inline extensions/ki_adminpanel/templates/scripts/activities.php:50]: very simple answer: because the field is not there. I just see that `$this->projects` is very different than `$activity['projects']`. There is too much "magic" going on in `getActivitiesData()`

Comment (kevinpapst) [inline extensions/ki_adminpanel/templates/scripts/activities.php:50]: True, in your version. Then why not adding "customerVisible" to "activity_get_projects" which you are using?
If not, we would loose that feature.

**Comment by kevinpapst** [comment]
👍 ready for merge?

**Comment by simonschaufi** [comment]
yes!
