### PR TITLE
[BUGFIX] Fix wrong id error when using "Open entry after the recording was stopped" option (resolves #541)

### LINKED ISSUE #541: Bug regarding the "Open entry after the recording was stopped" option
When enabling the "Open entry after the recording was stopped" option in the user preferences, when stopping the timer, a wrong popup appears, because the does not get the correct id (id is empty actually).

Sending a pull request with fix in a moment.

### PR DESCRIPTION
**Pull request by smoove**
Fix wrong id error when using "Open entry after the recording was stopped" option (resolves #541)

### CODE REVIEW

File: core/js/main.js [hunk 1]
```diff
@@ -362,11 +362,12 @@ function stopRecord() {
     $("#timeSheetTable>table>tbody>tr#timeSheetEntry"+currentRecording+">td").css( "color", "#FFF" );
     show_selectors();
     $.post("processor.php", { axAction: "stopRecord", axValue: 0, id: currentRecording},
-        function(){
+        function(response){
               ts_ext_reload();
               document.title = default_title;
               if (openAfterRecorded)
-                editRecord(currentRecording);
+                var data = jQuery.parseJSON(response);
```
Comment (simonschaufi) [inline core/js/main.js:369]: i think you forgot putting the block in { ... } here, or?

**Comment by smoove** [comment]
Yeah, sorry i'm not used to that coding style. Fixed now.
