### PR TITLE
Fix fixed rates

### LINKED ISSUE #551: Fixed rates totally broken
I just added a fixed rate to a task and expected that for that task I get that amount of money no matter how long I work on it. Is my understanding right of what a "fixed rate" means?

What I see in the time entry is 0. Even after editing the entry afterwards manually and set a fixed rate there again, the amount of money still is not considered.

@kevinpapst @ServiusHack can you say something to this?

### PR DESCRIPTION
**Pull request by simonschaufi**
FIXES #551 #523

Changes proposed in this pull request:
- total rewrite of fixed rates handling

TODO
- [x] project specific fixed rates in activities floater
- [x] creating new time entries and set the fixed rates from:
  - [x] project
  - [x] activity
  - [ ] make sure setting NULL values in db is allowed (was not the case in my installation)
- [x] delete fixed rate combination when project assignment is deleted

### CODE REVIEW

**Comment by simonschaufi** [comment]
@kevinpapst please test!
here is a **partially** exported sql dump. please import it on an existing project!
[fixed_rate.sql.txt](https://github.com/kimai/kimai/files/315084/fixed_rate.sql.txt)

**Comment by simonschaufi** [comment]
I have no idea whats going on here with git but it doesn't behave like I want!

**Comment by simonschaufi** [comment]
keine Ahnung woher der commit https://github.com/simonschaufi/kimai/commit/93ad547d80ce9d622920ef6735959ca5019c6c81 kommt

File: templates/scripts/floaters/add_edit_activity.php [hunk 1]
```diff
@@ -65,17 +65,48 @@
...
+                    </tr>
+                    <?php
+                    $assignedProjects = array();
+                    if (isset($this->selectedProjects) && is_array($this->selectedProjects)) {
+                        foreach ($this->selectedProjects as $selectedProject) {
+                            $assignedProjects[] = $selectedProject['projectID'];
+                            ?>
+                            <tr>
+                                <td>
+                                    <?php echo $this->escape($selectedProject['name']), $this->formHidden('assignedProjects[]', $selectedProject['projectID']); ?>
```
Comment (kevinpapst) [inline templates/scripts/floaters/add_edit_activity.php:83]: this could be a label connected to the input field

File: templates/scripts/floaters/add_edit_activity.php [hunk 2]
```diff
@@ -65,17 +65,48 @@
...
-                            'cols' => 30,
-                            'rows' => 5,
-                            'class' => 'comment'
-                        )); ?>
-                    </li>
-                </ul>
+            <fieldset id="projectstab">
+                <table class="projectsTable">
+                    <tr>
+                        <td><label style="text-align: left;"><?php echo $this->translate('projects') ?>:</label></td>
```
Comment (kevinpapst) [inline templates/scripts/floaters/add_edit_activity.php:71]: css vs inline?

File: templates/scripts/floaters/add_edit_activity.php (hunk 1 above)
Comment (simonschaufi) [inline templates/scripts/floaters/add_edit_activity.php:83]: this ist the same table like in the projects overlay. can be done/refactored later.

File: templates/scripts/floaters/add_edit_activity.php (hunk 2 above)
Comment (simonschaufi) [inline templates/scripts/floaters/add_edit_activity.php:71]: same like in projects overlay. needs "global" refactoring. not in this PR.

File: libraries/Kimai/Database/Mysql.php [hunk 3]
```diff
@@ -1119,32 +1135,84 @@ public function assign_projectToActivities($projectID, $activityIDs)
...
-        return $groupIDs;
+        return $projectIDs;
     }
 
     /**
-     * returns all the groups of the given activity
+     * @param $activityId
+     * @return bool|array
+     */
+    public function getProjectsByActivity($activityId)
```
Comment (kevinpapst) [inline libraries/Kimai/Database/Mysql.php]: what is this new function for? doesn't seem to be used?

Comment (simonschaufi) [inline libraries/Kimai/Database/Mysql.php]: removed.
