### PR TITLE
fixed server_prefix #402

### LINKED ISSUE #402: DB Tables not Properly Renamed During Installation
[Src downloaded 2014_07_10 from](https://github.com/kimai/kimai/releases/download/v0.9.3-rc.1/kimai_0.9.3.rc1.zip)

Steps that led to the following citation:
_"Error during installation!
Kimai is unable to create necessary tables because tables with the name name already exist. To update your existing installation please click here. Choose another table prefix or delete existing tables with this prefix in order to allow Kimai to perform a clean installation."_
### step_1)

During installation use a huge database table name prefix.

```
kimai_<about 100 characters>
```
### step_2)

Push button "Proceed" and enjoy the error message that says that the table name prefix should be about 64 chars max.
### step_3)

Edit the table name prefix by deleting characters from its end, e.g. by leaving the head part of the text the same.
### step_4)

Push button "Proceed" and enjoy the previously cited error message. :-)

### LINKED ISSUE #1082: Installation fails on mysqld because Indices are too large
#### Steps to reproduce
Download and install on mysqld (mysqld 10.1.26-MariaDB)
#### Kimai version [for example: dev 1.1.0.1389|github master|github develop]
dev v1.2.1.1393 (github master)
#### Relevant log entries from log file (debug tab or temporary/logfile.txt)

> [01.01.2018 16:02:11] -- begin install ----------------------------------                                
> [01.01.2018 16:02:12] [ERROR] in [CREATE TABLE `kimai18i_preferences` (`userID` int(10) NOT NULL,`option` varchar(255) NOT NULL,`value` varchar(255) NOT NULL,PRIMARY KEY (`userID`,`option`));] => s:63:"Specified
>  key was too long; max key length is 767 bytes (#1071)";                                                 
> [01.01.2018 16:02:17] [ERROR] in [CREATE TABLE `kimai18i_configuration` (`option` varchar(255) NOT NULL,`value` varchar(255) NOT NULL,PRIMARY KEY(`option`));] => s:63:"Specified key was too long; max key length 
> is 767 bytes (#1071)";                              
> [01.01.2018 16:02:26] [ERROR] in [INSERT INTO `kimai18i_preferences` (`userID`,`option`,`value`) VALUES('006128753', 'ui.rowlimit', '100'),('006128753', 'ui.skin', 'standard'),('006128753', 'ui.showCommentsByDef
> ault', '0'),('006128753', 'ui.hideOverlapLines', '1'),('006128753', 'ui.showTrackingNumber', '1'),('006128753', 'timezone', 'Europe/Berlin');] => s:56:"Table 'kimai.kimai18i_preferences' doesn't exist (#1146)"; 
> [01.01.2018 16:02:26] [ERROR] in [INSERT INTO `kimai18i_configuration` (`option`, `value`) VALUES('version', '1.2.1'),('login', '1'),('adminmail', 'admin@example.com'),('loginTries', '3'),('loginBanTime', '900')
> ,('revision', '1393'),('currency_name', 'Euro'),('currency_sign', '€'),('currency_first', '0'),('show_update_warn', '1'),('check_at_startup', '0'),('show_daySeperatorLines', '1'),('show_gabBreaks', '0'),('show_R
> ecordAgain', '1'),('show_TrackingNr', '1'),('date_format_0', 'dd.mm.yy'),('date_format_1', '%d.%m.'),('date_format_2', '%d.%m.%Y'),('date_format_3', 'd.m.Y'),('table_time_format', '%H:%M'),('language', 'de'),('r
> oundPrecision', '0'),('decimalSeparator', ','),('durationWithSeconds', '0'),('exactSums', '0'),('defaultVat', '0'),('editLimit', '0'),('roundTimesheetEntries', '0'),('roundMinutes', '0'),('roundSeconds', '0'),('
> allowRoundDown', '0'),('defaultStatusID', '1')] => s:58:"Table 'kimai.kimai18i_configuration' doesn't exist (#1146)";                                                                                              
> [01.01.2018 16:02:26] -- showing install error --------------------------

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #402 - tackles a problem while writing the config during installation
Fixes #1082 - fixes key length for utf8mb4 collation

### CODE REVIEW

File: installer/processor.php [hunk 1]
```diff
@@ -186,8 +186,9 @@ function getpass()
 
         $db_error = false;
         $result = false;
+        $config = new Kimai_Config(array());
 
-        $database = new Kimai_Database_Mysql($result, false);
+        $database = new Kimai_Database_Mysql(, false);
```
Comment (simonschaufi) [inline installer/processor.php]: this doesn't look right

**Review by simonschaufi — CHANGES_REQUESTED** [review]

**Comment by kevinpapst** [comment]
I wasn't ready, sorry ;-) that was a commit in a hurry^^
I haven't changed database structure in a long time, so please check if I may hav forgotten something

File: installer/processor.php (hunk 1 above)
Comment (kevinpapst) [reply installer/processor.php]: LOL, so true - I seem to have hit STRG-Z before sommitting

**Review by simonschaufi — APPROVED** [review]
